[ARC-1812]refactor base fragment
giorgiqemoklidze/MovieApp pull request #5
Opened 2021-11-01 11:48 UTC by giorgiqemoklidze

https://spaceneobank.atlassian.net/browse/ARC-1812

2021-11-01 11:53 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
> +    protected abstract fun getViewModelClass(): Class<VM>
protected მგონი არუნდა აბსტრაქტზე

2021-11-01 12:55 UTC, AnaRusadze requested changes

2021-11-01 12:55 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
> +    abstract fun onViewCreated()
ეს ფუნქცია ზედმეტია

2021-11-01 12:55 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
> +    abstract fun inflate(layoutInflater: LayoutInflater, container: ViewGroup?, attachToRoot: Boolean): VB
ესეც ზედმეტია, ინფლეიტი ისედაც კეთდება onCreateViewში

2021-11-01 14:15 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
> +    protected abstract fun getViewModelClass(): Class<VM>
done

2021-11-01 14:15 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
> +    abstract fun onViewCreated()
done

2021-11-01 14:16 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
> +    abstract fun inflate(layoutInflater: LayoutInflater, container: ViewGroup?, attachToRoot: Boolean): VB
bindings vigebdi amit fragmentidan mara exla gadavakete da sxvanairad vigeb mgoni is ufro sworia exla rogorc vqeni

2021-11-01 14:16 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
> +    abstract fun inflate(layoutInflater: LayoutInflater, container: ViewGroup?, attachToRoot: Boolean): VB
done

2021-11-01 14:27 UTC, AleksandreGalogreBaramidze approved these changes

2021-11-01 14:31 UTC, andguladzeshio commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
> +    abstract fun getViewModelClass(): Class<VM>
ბარემ ესეც ცვლადად გამოგეცხადებინა

2021-11-01 14:33 UTC, andguladzeshio commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
>          if (_binding == null) {
ონქრიეითვიუში თუ შემოდის მგონი ყველა ვარიანტში ნალია ბაინდინგი

2021-11-01 14:40 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-01 14:45 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
>          if (_binding == null) {
ეშმაკს არ სზინავს ხოიცი თავი სულ უნდა დაიზღვიო

2021-11-01 14:45 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
>          if (_binding == null) {
;დ

2021-11-02 11:16 UTC, AnaRusadze requested changes

2021-11-02 11:16 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/moviedetails/MovieDetailsFragment.kt
>      private var posterUrl = ""
ეს ცვლადი არ უნდა იყოს ფრაგმენტში

2021-11-02 11:16 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/moviedetails/MovieDetailsFragment.kt
val imageLink = IMAGE_URL + it.data!!.posterPath ეს ლოგიკა აქ არ უნდა იყოს. სხვებს უწერიათ დატა კლასშივე ფუნქცია რომელიც აბრუნებს პოსტერს

2021-11-02 11:16 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/moviedetails/MovieDetailsFragment.kt
ობსერვის ექსთენშენი გააკეთე

2021-11-02 11:16 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesFragment.kt
> +        const val TOAST_TIME = 1000
private const val

2021-11-02 11:16 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/splashscreen/SplashFragment.kt
> +        const val SPLASH_TIME = 1500L
private const val

2021-11-02 14:16 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/ui/moviedetails/MovieDetailsFragment.kt
>      private var posterUrl = ""
ეს მარტო baze fragment  ის რეფაქტორის თასქი იყო შემდეგ თასქში მაქ ამის რეფაქტორი

2021-11-02 14:18 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/ui/splashscreen/SplashFragment.kt
> +        const val SPLASH_TIME = 1500L
ესეც შემდეგ თასქში მაქ :D

2021-11-02 14:18 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesFragment.kt
> +        const val TOAST_TIME = 1000
ესეც შემდეგ თასქში მაქ :D

2021-11-02 14:19 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/ui/moviedetails/MovieDetailsFragment.kt
ესეც შემდეგ თასქში მაქ :D

2021-11-02 14:25 UTC, AnaRusadze requested changes

2021-11-02 14:25 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
> +    abstract val bindingInflater: (LayoutInflater, ViewGroup?, Boolean) -> VB
abstract val bindingInflater: (LayoutInflater, ViewGroup?, Boolean) -> VB შვილს არ უნდა სჭირდებოდეს ეს პარამეტრები. სცადე რომ სხვანაირად გააკეთო ინფლეიტი. https://stackoverflow.com/questions/64819181/how-to-make-basefragment-with-view-binding

2021-11-02 15:12 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/BaseFragment.kt
> +    abstract val bindingInflater: (LayoutInflater, ViewGroup?, Boolean) -> VB
ასე სწორია ?

2021-11-03 08:33 UTC, AnaRusadze approved these changes

2021-11-03 08:34 UTC, merged