[ARC-1812] refactored recycler , paging ,viewModels and fragments
giorgiqemoklidze/MovieApp pull request #6
Opened 2021-11-03 14:22 UTC by giorgiqemoklidze

https://spaceneobank.atlassian.net/browse/ARC-1812

2021-11-03 15:15 UTC, AleksandreGalogreBaramidze approved these changes

2021-11-04 11:05 UTC, AnaRusadze requested changes

2021-11-04 11:05 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/moviedetails/MovieDetailsFragment.kt
> +    private fun observes(viewModel: MovieDetailsViewModel) {
onBindViewModel-ის ფუნქციის არსი ისაა, რომ ცალკე observe-ს ფუნქციის შექმნა არ დაგჭირდეს

2021-11-04 11:05 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesFragment.kt
> +        const val IMAGE_URL = "https://image.tmdb.org/t/p/w500/"
ამას სად იყენებ? ფრაგმენტში არა ხო?

2021-11-04 11:05 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesViewModel.kt
> +                getTopRated(currentPage + 1)
1 უნდა იყოს კონსტანტის ცვლადი NEXT_PAGE ან მსგავსი

2021-11-04 11:05 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/movies/adapters/MoviesRecyclerAdapter.kt
> +        holder.binding.movieImg.setOnClickListener { getMovieId(data[position].id) }
with(holder.binding.movieImg)

2021-11-04 11:05 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/ui/movies/adapters/RecyclerOnScrollListener.kt
> +        val moreThanShowedItems = recyclerLayoutManager.itemCount >= 20
page size გარედან გადმოაწოდე რომ სხვა დროს სხვა ზომა რომ დაგჭირდეს, ლისენერი მოქნილი იყოს

2021-11-04 11:24 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesFragment.kt
> +        const val IMAGE_URL = "https://image.tmdb.org/t/p/w500/"
არა დატა კლასში მაქ გამოძახებული

2021-11-04 11:28 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/ui/moviedetails/MovieDetailsViewModel.kt
> +    var posterUrl = ""
დასეივების დროს პოსტ ურლ უნდა შეინახოს და სადმე უნდა მქონოდა გამოცხადებული რომ  მერე შენახვის ფუნქციაში გადამეცა და ვიუმოდელში ვინახავ და შენახვის დროს ამ ცვლადს ვაწვდი

2021-11-04 11:30 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/ui/moviedetails/MovieDetailsFragment.kt
> +    private fun observes(viewModel: MovieDetailsViewModel) {
ანუ ობზერვში რაც მიწერია ყველაფერი ონბინდვიუმოდელში გადავიტანო პირდაპირ ? წაკითხვის მხრივ მგონი ასე უფრო კითხვადია და მაგიტომ მაქ

2021-11-04 11:41 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/ui/movies/adapters/MoviesRecyclerAdapter.kt
> +        holder.binding.movieImg.setOnClickListener { getMovieId(data[position].id) }
done

2021-11-04 11:41 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/ui/movies/adapters/RecyclerOnScrollListener.kt
> +        val moreThanShowedItems = recyclerLayoutManager.itemCount >= 20
done

2021-11-04 11:41 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/movieapp/ui/movies/MoviesViewModel.kt
> +                getTopRated(currentPage + 1)
done

2021-11-04 12:04 UTC, andguladzeshio approved these changes

2021-11-05 12:38 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-05 12:57 UTC, AnaRusadze approved these changes

2021-11-05 12:57 UTC, merged